//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace PracticaAlmacenes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.ProductosAlmacen = new HashSet<ProductosAlmacen>();
            this.Etiqueta = new HashSet<Etiqueta>();
        }
    
        public int idProducto { get; set; }
        public string nombre { get; set; }
        public string fabricante { get; set; }
        public int pcoste { get; set; }
        public Nullable<int> pventa { get; set; }
        public string descripcion { get; set; }
        [DisplayName("Categoria")]
        [Range(1, 4, ErrorMessage = "Valores de 1 a 4")]
        public int idCategoria { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductosAlmacen> ProductosAlmacen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Etiqueta> Etiqueta { get; set; }
    }
}
